### ISSUE TITLE
大佬，我设置好短信服务端后，用手机号登陆会返回这个，是怎么回事啊

### ISSUE THREAD

**Issue by yongjie9** [cdle/sillyGirl#14]
Get "http://47.245.257.4:5701": read tcp 172.17.36.11:35786->47.245.257.4:5701: i/o timeout

**Comment by lovelykids** [comment]
青龙无法访问
估计设置错误，不知道你上面的ip是不是故意改错的。

**Comment by yongjie9** [comment]
我故意改的

**Comment by TangTree** [comment]
我的也是这样，搞了好几遍都这样，当时发送cookie没问题，只有短信登录这样
