### ISSUE TITLE
编译成功后 扫码无反应 麻烦看看呢

### ISSUE THREAD

**Issue by isslower** [cdle/sillyGirl#37]
![微信截图_20211118115704](https://user-images.githubusercontent.com/45580748/142349065-4027bf5f-af82-4031-a2dc-a8772db9a130.png)
![image](https://user-images.githubusercontent.com/45580748/142349221-0211210a-8030-4826-b9dd-0752f99d86f5.png)
设置了一下内容
# 傻妞机器人名
# 傻妞http服务端口
# 设置青龙面板地址
# 设置青龙openapi的client_id参数
# 设置青龙openapi的client_secret参数

**Comment by cdle** [comment]
你号不行，换个试试
