### ISSUE TITLE
傻妞设置的指令该发在哪里

### ISSUE THREAD

**Issue by hackmln** [cdle/sillyGirl#38]
机器人发机器人没反应
./sillyGirl后输入也没反应
自己的QQ发机器人也没反应
机器人发给自己的QQ也没反应

**Comment by SamDudu** [comment]
我也遇到一样的问题
（1）执行一键安装命令
s=sillyGirl;a=arm64;if [[ $(uname -a | grep "x86_64") != "" ]];then a=amd64;fi ;if [ ! -d $s ];then mkdir $s;fi ;cd $s;wget https://mirror.ghproxy.com/https://github.com/cdle/${s}/releases/download/main/${s}_linux_$a -O $s && chmod 777 $s;pkill -9 $s;$(pwd)/$s 
（2）设置配置文件
s=/etc/sillyGirl;if [ ! -d $s ];then mkdir $s; fi; echo "set qq masters 592399989" > /etc/sillyGirl/sets.conf
（3）重启傻妞
（4）自己的QQ发机器人也没反应
（5）机器人发给自己的QQ也没反应

**Comment by MK-D-Luffy** [comment]
我的是有些api指令能识别执行，有些不行
![1](https://user-images.githubusercontent.com/60993277/142798752-a29ed86f-6bad-4192-9af1-39d0f24c331f.png)
![2](https://user-images.githubusercontent.com/60993277/142798905-bf7af8a6-1cff-472d-8bd3-8f7d45e82ad1.png)
上面的set pinQQ能识别到，查询就识别不到了，不知道为啥
