### ISSUE TITLE
怎么退出静默模式？重启后不会回消息.

### ISSUE THREAD

**Issue by sadnecc** [cdle/sillyGirl#5]
发送重启到qq以后 ，SSH提示进入静默模式 。怎么退出这个静默模式？
目前问题是输入重启以后， 查询，等命令不能用，但是发 二次元， 可以收到图片， 再发查询，又能返回信息.
能否加入扫码录入key？

**Comment by sadnecc** [comment]
另，单QQ能否传入多个key ，并查询？

**Comment by 717009629** [comment]
> 发送重启到qq以后 ，SSH提示进入静默模式 。怎么退出这个静默模式？
> 目前问题是输入重启以后， 查询，等命令不能用，但是发 二次元， 可以收到图片， 再发查询，又能返回信息.
> 能否加入扫码录入key？

kill pid

**Comment by 717009629** [comment]
> 另，单QQ能否传入多个key ，并查询？

可以的
