### ISSUE TITLE
改不了地址了

### ISSUE THREAD

**Issue by lishangyi** [cdle/sillyGirl#69]
set qinglong host http://127.0.0.1:5700/
后地址还是原来的，不会改变。
改密钥和客户端也是不会改变

**Comment by muzikeji** [comment]
先 delete&nbsp;qinglong host 再试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lidream ***@***.***&gt;
发送时间: 2022年2月6日 12:37
收件人: cdle/sillyGirl ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [cdle/sillyGirl] 改不了地址了 (Issue #69)





 
set qinglong host http://127.0.0.1:5700/
 后地址还是原来的，不会改变。
 改密钥和客户端也是不会改变
