### ISSUE TITLE
请问下提示“加载设备信息失败”是什么问题呢

### ISSUE THREAD

**Issue by wangtao19961024** [cdle/sillyGirl#9]
2021/09/27 11:01:53.068 [Q] 加载设备信息失败: failed to unmarshal json message: readObjectStart: expect { or n, but found ?, error found in #1 byte of ...|?|..., bigger context ...|?|...

**Comment by HDong2021** [comment]
新版我也是这样

**Comment by wangtao19961024** [comment]
> 新版我也是这样

删除/etc/sillyGirl/sillyGirl.cache 这个文件

**Comment by HDong2021** [comment]
删除这个文件会重新生成这个文件啊

**Comment by wangtao19961024** [comment]
> 删除这个文件会重新生成这个文件啊

是的 删除原来旧的这个文件

**Comment by wangtao19961024** [comment]
我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因  我的已经恢复正常 重新配置了

**Comment by HDong2021** [comment]
那个短信登录你们会整 吗

**Comment by wangtao19961024** [comment]
> 那个短信登录你们会整 吗

还在摸索中，没找到大佬提供的文档

**Comment by HDong2021** [comment]
> > 那个短信登录你们会整 吗
> 
> 还在摸索中，没找到大佬提供的文档

好象得接入插件，我也没弄懂

**Comment by HDong2021** [comment]
> 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了

发送升级检查后也没反应，你们会吗

**Comment by wangtao19961024** [comment]
> > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> 
> 发送升级检查后也没反应，你们会吗

看日志，有时候傻妞有回复  但是没发送出来

**Comment by HDong2021** [comment]
> > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > 
> > 
> > 发送升级检查后也没反应，你们会吗
> 
> 看日志，有时候傻妞有回复 但是没发送出来

看了，也是没反应

**Comment by DabaiBy** [comment]
> > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > 
> > > 
> > > 发送升级检查后也没反应，你们会吗
> > 
> > 
> > 看日志，有时候傻妞有回复 但是没发送出来
> 
> 看了，也是没反应

发送的是“升级检查”还是“升级” ？  升级检查不是指令 升级才是指令

**Comment by HDong2021** [comment]
> > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > 
> > > > 
> > > > 发送升级检查后也没反应，你们会吗
> > > 
> > > 
> > > 看日志，有时候傻妞有回复 但是没发送出来
> > 
> > 
> > 看了，也是没反应
> 
> 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令

发了升级命令，然后机器人只提示核心检查更新，然后没有反应了

**Comment by DabaiBy** [comment]
> > > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > > 
> > > > > 
> > > > > 发送升级检查后也没反应，你们会吗
> > > > 
> > > > 
> > > > 看日志，有时候傻妞有回复 但是没发送出来
> > > 
> > > 
> > > 看了，也是没反应
> > 
> > 
> > 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令
> 
> 发了升级命令，然后机器人只提示核心检查更新，然后没有反应了

看日志吧，可以重启下机器在试试

**Comment by wangtao19961024** [comment]
> > > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > > 
> > > > > 
> > > > > 发送升级检查后也没反应，你们会吗
> > > > 
> > > > 
> > > > 看日志，有时候傻妞有回复 但是没发送出来
> > > 
> > > 
> > > 看了，也是没反应
> > 
> > 
> > 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令
> 
> 发了升级命令，然后机器人只提示核心检查更新，然后没有反应了

检查日志，重启机器人试试

**Comment by HDong2021** [comment]
> > > > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > > > 
> > > > > > 
> > > > > > 发送升级检查后也没反应，你们会吗
> > > > > 
> > > > > 
> > > > > 看日志，有时候傻妞有回复 但是没发送出来
> > > > 
> > > > 
> > > > 看了，也是没反应
> > > 
> > > 
> > > 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令
> > 
> > 
> > 发了升级命令，然后机器人只提示核心检查更新，然后没有反应了
> 
> 检查日志，重启机器人试试

没用，真傻了，删了，准备重来了

**Comment by HDong2021** [comment]
> > > > > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > > > > 
> > > > > > > 
> > > > > > > 发送升级检查后也没反应，你们会吗
> > > > > > 
> > > > > > 
> > > > > > 看日志，有时候傻妞有回复 但是没发送出来
> > > > > 
> > > > > 
> > > > > 看了，也是没反应
> > > > 
> > > > 
> > > > 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令
> > > 
> > > 
> > > 发了升级命令，然后机器人只提示核心检查更新，然后没有反应了
> > 
> > 
> > 检查日志，重启机器人试试
> 
> 没用，真傻了，删了，准备重来了

重装好，设备加载失败了

**Comment by wangtao19961024** [comment]
> > > > > > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 发送升级检查后也没反应，你们会吗
> > > > > > > 
> > > > > > > 
> > > > > > > 看日志，有时候傻妞有回复 但是没发送出来
> > > > > > 
> > > > > > 
> > > > > > 看了，也是没反应
> > > > > 
> > > > > 
> > > > > 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令
> > > > 
> > > > 
> > > > 发了升级命令，然后机器人只提示核心检查更新，然后没有反应了
> > > 
> > > 
> > > 检查日志，重启机器人试试
> > 
> > 
> > 没用，真傻了，删了，准备重来了
> 
> 重装好，设备加载失败了

删除/etc/sillyGirl/sillyGirl.cache

**Comment by HDong2021** [comment]
> > > > > > > > > > 我还删除sillyGirl/data 这个目录 不知到是不是还有这个的原因 我的已经恢复正常 重新配置了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 发送升级检查后也没反应，你们会吗
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 看日志，有时候傻妞有回复 但是没发送出来
> > > > > > > 
> > > > > > > 
> > > > > > > 看了，也是没反应
> > > > > > 
> > > > > > 
> > > > > > 发送的是“升级检查”还是“升级” ？ 升级检查不是指令 升级才是指令
> > > > > 
> > > > > 
> > > > > 发了升级命令，然后机器人只提示核心检查更新，然后没有反应了
> > > > 
> > > > 
> > > > 检查日志，重启机器人试试
> > > 
> > > 
> > > 没用，真傻了，删了，准备重来了
> > 
> > 
> > 重装好，设备加载失败了
> 
> 删除/etc/sillyGirl/sillyGirl.cache

删除他，还有得删除配置文件set那个

**Comment by HDong2021** [comment]
升级显示检查升级，不会升级怎么解决
