### ISSUE TITLE
傻妞插件cron定时发送没反应

### ISSUE THREAD

**Issue by Alone7707** [cdle/sillyGirl#94]
插件设置了cron定时发送，但是到点没反应，不发送

**Comment by Alone7707** [comment]
> 插件设置了cron定时发送，但是到点没反应，不发送

**Comment by muzikeji** [comment]
菜

**Comment by muzikeji** [comment]
我只能说程序一切正常，其他都是自己问题。

**Comment by Alone7707** [comment]
> 菜

不接打不帮忙就算了，在这说菜几个意思？

**Comment by Alone7707** [comment]
> 我只能说程序一切正常，其他都是自己问题。



> 菜

有点家教吗，你没义务帮人，无视不行？非得拿自己的素质当耍，不说话没人当你哑巴的好吧

**Comment by Alone7707** [comment]
> 我只能说程序一切正常，其他都是自己问题。

这里是ISSUES，意思是问题，这里是提问题解决问题的地方，不回答拉到，别在这阴阳怪气的ok？

**Comment by muzikeji** [comment]
不看文档，你永远不会。
> > 我只能说程序一切正常，其他都是自己问题。
> 
> 
> 
> 这里是ISSUES，意思是问题，这里是提问题解决问题的地方，不回答拉到，别在这阴阳怪气的ok？

**Comment by Alone7707** [comment]
> 不看文档，你永远不会。
> 
> > > 我只能说程序一切正常，其他都是自己问题。
> > 
> > 
> > 这里是ISSUES，意思是问题，这里是提问题解决问题的地方，不回答拉到，别在这阴阳怪气的ok？

所以，插件文档在哪？我就是找不到菜来这问的ok？

**Comment by muzikeji** [comment]
TG

**Comment by muzikeji** [comment]
> 插件设置了cron定时发送，但是到点没反应，不发送

// [rule: 外卖]
// [cron: 30 11,16 * * *]
比如我这个11:30 和16:30 和平时写其他的程序规则一样的，只需要加// [cron: ]
时间规则参考这个站https://tool.lu/crontab/
